[package]
name = "kadrustlia"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
sha2 = "0.10.8"
tokio = { version = "1", features = ["full"] }
tonic = { version = "0.8", features = ["transport"] }
prost = "0.11"
prost-types = "0.11"

[build-dependencies]
tonic-build = "0.8"