version: '3.8'

services:
  node:
    build: .
    command: ["./kadrustlia"]
    networks:
      my_network:
    deploy:
      replicas: 50
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
    restart: always

networks:
  my_network:
    driver: bridge