version: "3"
services:
  bootNode:
    image: kademlia:latest 
    ports:
      - "50051:50051"
    environment: 
      - BN=1
    networks:
      - kademlia_network

  kademliaNodes:
    image: kademlia:latest 
    depends_on:
      - bootNode
    environment: 
      - BN=0
      - BNAD=bootNode
      - BNPT=50051
    deploy:
      mode: replicated
      replicas: 5
    stdin_open: true
    tty: true
    networks:
      - kademlia_network
      
networks:
  kademlia_network:
