version: "3"
services:
  bootNode:
    image: kademlia:latest 
    ports:
      - "5678:5678"
    environment: 
      - BN=1
    networks:
      - kademlia_network
    stdin_open: true
    tty: true
    
  kademliaNodes:
    image: kademlia:latest 
    depends_on:
      - bootNode
    environment:
      - LISTENER=0
      - BN=0
      - BNAD=bootNode
      - BNPT=5678
    deploy:
      mode: replicated
      replicas: 5
    stdin_open: true
    tty: true
    networks:
      - kademlia_network

networks:
  kademlia_network: